FROM python:2.7.15

MAINTAINER Joshua Eagle

WORKDIR /root/

COPY . /root/gate-keeper

WORKDIR /root/gate-keeper/

RUN pip install -r requirements.txt

WORKDIR /root/gate-keeper/src/python

EXPOSE 5000

CMD ["python", "app.py"]
